install: Don't run postInstall script
Something about the postInstall script isn't working on Yarn v2 (but it
works with Yarn v1). It throws the following error when installing:

```

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/node/app/node_modules/java/build/jvm_dll_path.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at /home/node/app/node_modules/java/postInstall.js:22:8
    at /home/node/app/node_modules/find-java-home/index.js:133:31
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

We think this is because of a race between running the postInstall
script and node-gyp creating the build directory, but haven't confirmed.

As a quick hack, this commit removes the postInstall script entirely --
and we'll explicitly call it after the package has been installed from
our postInstall hook.